name: Setup Build
description: >
  Checkout repositories and build dependencies

runs:
  using: composite
  steps:
    - name: Checkout tools
      uses: actions/checkout@v4
      with:
        path: 'aws-kotlin-repo-tools'
        repository: 'awslabs/aws-kotlin-repo-tools'
        ref: 'kn-main'
        sparse-checkout: |
          .github

    - name: Checkout aws-crt-kotlin
      uses: ./aws-kotlin-repo-tools/.github/actions/checkout-head
      with:
        # checkout aws-crt-kotlin as a sibling which will automatically make it an included build
        path: 'aws-crt-kotlin'
        repository: 'awslabs/aws-crt-kotlin'
        submodules: 'true'

    # Cache the Kotlin/Native toolchain based on the input Kotlin version from version catalog
    # see https://kotlinlang.org/docs/native-improving-compilation-time.html
    - name: Cache Kotlin Native toolchain
      uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-konan-

    - name: Configure JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        cache: 'gradle'